CREATE DATABASE IF NOT EXISTS ${WORDPRESS_DB_DATABASE} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${WORDPRESS_DB_USER}'@'%' IDENTIFIED BY '${WORDPRESS_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON ${WORDPRESS_DB_DATABASE}.* TO '${WORDPRESS_DB_USER}'@'%';
FLUSH PRIVILEGES;